# -*- coding: utf-8 -*-
"""Selamat Datang di Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from google.colab import files
from openpyxl import load_workbook
import os

# === Upload file dari komputer ===
uploaded = files.upload()

# Ambil nama file yang diupload
input_file = list(uploaded.keys())[0]

# Tambah akhiran "hasil_konversi.xlsx"
name, ext = os.path.splitext(input_file)
output_file = f"{name}_hasil_konversi{ext}"

# === Buka Excel ===
wb = load_workbook(input_file)
ws = wb.active

# === Kolom essay (misalnya Response 11–15 di kolom C-G = 3-7) ===
essay_columns = [3, 4, 5, 6, 7]

for row in range(2, ws.max_row + 1):
    for col in essay_columns:
        cell = ws.cell(row=row, column=col)
        if cell.value:
            text = str(cell.value).replace("\n", " ").replace("\r", " ").replace("*", "")
            while "  " in text:
                text = text.replace("  ", " ")
            cell.value = text.strip()

# === Simpan hasil ===
wb.save(output_file)
files.download(output_file)